version: '3.8'

services:
  health-monitor:
    build: .
    ports:
      - "8080:8080"  # Web UI and API
      - "9091:9091"  # Metrics
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
