apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "health-caretaker.fullname" . }}
  labels:
    {{- include "health-caretaker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "health-caretaker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "health-caretaker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "health-caretaker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: {{ .Values.env.WEB_PORT }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.env.METRICS_PORT }}
              protocol: TCP
          env:
            - name: WEB_PORT
              value: {{ .Values.env.WEB_PORT | quote }}
            - name: METRICS_PORT
              value: {{ .Values.env.METRICS_PORT | quote }}
            - name: METRICS_ENABLED
              value: {{ .Values.env.METRICS_ENABLED | quote }}
            - name: METRICS_PATH
              value: {{ .Values.env.METRICS_PATH | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: web
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: web
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "health-caretaker.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
