{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "health-caretaker.fullname" . }}
  labels:
    {{- include "health-caretaker.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "health-caretaker.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.env.WEB_PORT }}
        - protocol: TCP
          port: {{ .Values.env.METRICS_PORT }}
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    - {} # Allow all egress traffic
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
