apiVersion: v1
kind: Service
metadata:
  name: {{ include "health-caretaker.fullname" . }}
  labels:
    {{- include "health-caretaker.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: web
      protocol: TCP
      name: web
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "health-caretaker.selectorLabels" . | nindent 4 }}
